<?php
/**
 * EcosystemsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  MetaFab
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MetaFab API
 *
 * Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.5.0
 * Contact: metafabproject@gmail.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace MetaFab\Test\Api;

use \MetaFab\Configuration;
use \MetaFab\ApiException;
use \MetaFab\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * EcosystemsApiTest Class Doc Comment
 *
 * @category Class
 * @package  MetaFab
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EcosystemsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for approveEcosystemGame
     *
     * Approve ecosystem game.
     *
     */
    public function testApproveEcosystemGame()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for authEcosystem
     *
     * Authenticate ecosystem.
     *
     */
    public function testAuthEcosystem()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for authProfile
     *
     * Authenticate profile.
     *
     */
    public function testAuthProfile()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for authProfilePlayer
     *
     * Authenticate profile player.
     *
     */
    public function testAuthProfilePlayer()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createEcosystem
     *
     * Create ecosystem.
     *
     */
    public function testCreateEcosystem()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createProfile
     *
     * Create profile.
     *
     */
    public function testCreateProfile()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createProfilePlayer
     *
     * Create profile player.
     *
     */
    public function testCreateProfilePlayer()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getEcosystem
     *
     * Get ecosystem.
     *
     */
    public function testGetEcosystem()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getEcosystemGame
     *
     * Get ecosystem game.
     *
     */
    public function testGetEcosystemGame()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getEcosystemGames
     *
     * Get ecosystem games.
     *
     */
    public function testGetEcosystemGames()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProfileGame
     *
     * Get profile game.
     *
     */
    public function testGetProfileGame()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProfileGames
     *
     * Get profile games.
     *
     */
    public function testGetProfileGames()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for unapproveEcosystemGame
     *
     * Unapprove ecosystem game.
     *
     */
    public function testUnapproveEcosystemGame()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateEcosystem
     *
     * Update ecosystem.
     *
     */
    public function testUpdateEcosystem()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateProfile
     *
     * Update profile.
     *
     */
    public function testUpdateProfile()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateProfilePlayer
     *
     * Update profile player.
     *
     */
    public function testUpdateProfilePlayer()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
