<?php
/**
 * ExchangesApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  MetaFab
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MetaFab API
 *
 * Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.2
 * Contact: metafabproject@gmail.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace MetaFab\Test\Api;

use \MetaFab\Configuration;
use \MetaFab\ApiException;
use \MetaFab\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ExchangesApiTest Class Doc Comment
 *
 * @category Class
 * @package  MetaFab
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ExchangesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createExchange
     *
     * Create exchange.
     *
     */
    public function testCreateExchange()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getExchangeOffer
     *
     * Get exchange offer.
     *
     */
    public function testGetExchangeOffer()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getExchangeOffers
     *
     * Get exchange offers.
     *
     */
    public function testGetExchangeOffers()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getExchanges
     *
     * Get exchanges.
     *
     */
    public function testGetExchanges()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for removeExchangeOffer
     *
     * Remove exchange offer.
     *
     */
    public function testRemoveExchangeOffer()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for setExchangeOffer
     *
     * Set exchange offer.
     *
     */
    public function testSetExchangeOffer()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for useExchangeOffer
     *
     * Use exchange offer.
     *
     */
    public function testUseExchangeOffer()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for withdrawFromExchange
     *
     * Withdraw from exchange.
     *
     */
    public function testWithdrawFromExchange()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
