<?php
/**
 * ItemsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  MetaFab
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MetaFab API
 *
 * Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: metafabproject@gmail.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace MetaFab\Test\Api;

use \MetaFab\Configuration;
use \MetaFab\ApiException;
use \MetaFab\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ItemsApiTest Class Doc Comment
 *
 * @category Class
 * @package  MetaFab
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ItemsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for batchMintCollectionItems
     *
     * Batch mint collection items.
     *
     */
    public function testBatchMintCollectionItems()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for batchTransferCollectionItems
     *
     * Batch transfer collection items.
     *
     */
    public function testBatchTransferCollectionItems()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for burnCollectionItem
     *
     * Burn collection item.
     *
     */
    public function testBurnCollectionItem()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createCollection
     *
     * Create collection.
     *
     */
    public function testCreateCollection()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createCollectionItem
     *
     * Create collection item.
     *
     */
    public function testCreateCollectionItem()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCollectionApproval
     *
     * Get collection approval.
     *
     */
    public function testGetCollectionApproval()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCollectionItem
     *
     * Get collection item.
     *
     */
    public function testGetCollectionItem()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCollectionItemBalance
     *
     * Get collection item balance.
     *
     */
    public function testGetCollectionItemBalance()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCollectionItemBalances
     *
     * Get collection item balances.
     *
     */
    public function testGetCollectionItemBalances()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCollectionItemSupplies
     *
     * Get collection item supplies.
     *
     */
    public function testGetCollectionItemSupplies()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCollectionItemSupply
     *
     * Get collection item supply.
     *
     */
    public function testGetCollectionItemSupply()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCollectionItemTimelock
     *
     * Get collection item timelock.
     *
     */
    public function testGetCollectionItemTimelock()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCollectionItems
     *
     * Get collection items.
     *
     */
    public function testGetCollectionItems()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCollectionRole
     *
     * Get collection role.
     *
     */
    public function testGetCollectionRole()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCollections
     *
     * Get collections.
     *
     */
    public function testGetCollections()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for grantCollectionRole
     *
     * Grant collection role.
     *
     */
    public function testGrantCollectionRole()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for mintCollectionItem
     *
     * Mint collection item.
     *
     */
    public function testMintCollectionItem()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for revokeCollectionRole
     *
     * Revoke collection role.
     *
     */
    public function testRevokeCollectionRole()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for setCollectionApproval
     *
     * Set collection approval.
     *
     */
    public function testSetCollectionApproval()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for setCollectionItemTimelock
     *
     * Set collection item timelock.
     *
     */
    public function testSetCollectionItemTimelock()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for transferCollectionItem
     *
     * Transfer collection item.
     *
     */
    public function testTransferCollectionItem()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
