<?php
/**
 * LootboxesApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  MetaFab
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MetaFab API
 *
 * Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: metafabproject@gmail.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace MetaFab\Test\Api;

use \MetaFab\Configuration;
use \MetaFab\ApiException;
use \MetaFab\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * LootboxesApiTest Class Doc Comment
 *
 * @category Class
 * @package  MetaFab
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class LootboxesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createLootboxManager
     *
     * Create lootbox manager.
     *
     */
    public function testCreateLootboxManager()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getLootboxManagerLootbox
     *
     * Get lootbox manager lootbox.
     *
     */
    public function testGetLootboxManagerLootbox()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getLootboxManagerLootboxes
     *
     * Get lootbox manager lootboxes.
     *
     */
    public function testGetLootboxManagerLootboxes()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getLootboxManagers
     *
     * Get lootbox managers.
     *
     */
    public function testGetLootboxManagers()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for openLootboxManagerLootbox
     *
     * Open lootbox manager lootbox.
     *
     */
    public function testOpenLootboxManagerLootbox()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for removeLootboxManagerLootbox
     *
     * Remove lootbox manager lootbox.
     *
     */
    public function testRemoveLootboxManagerLootbox()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for setLootboxManagerLootbox
     *
     * Set lootbox manager lootbox.
     *
     */
    public function testSetLootboxManagerLootbox()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
